backend:
  name: github
  repo: citricssonvivot/citricssonvivot-web
  branch: main
  auth_endpoint: https://github.com/login/oauth/authorize

logo_url: https://raw.githubusercontent.com/citricssonvivot/citricssonvivot-web/main/images/LOGO%20c%C3%ADtrics%20son%20vivot%20SENSE%20FONS.png

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.html"
        label: "Página Principal"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string", default: "Cítrics Son Vivot" }
          - { label: "Descripción", name: "description", widget: "text" }
